update lxml code for latest version
fixes
ValueError: Unicode strings with encoding declaration are not supported.
Please use bytes input or XML fragments without declaration.

lxml prefers to be passed bytes because xml files will include an
encoding declaration in the header e.g:
`<?xml version='1.0' encoding='UTF-8'?>`